### ISSUE TITLE
Pull remaining jar dependencies from jCenter/mavenCentral

### ISSUE THREAD

**Issue by krt16s** [raphaelm/opacclient#296]
There are quite some jar files at https://github.com/raphaelm/opacclient/tree/master/opacclient/meaningdetector/libs , most of them should be available from the default repositories.

**Comment by raphaelm** [comment]
While your point seems to be valid and I believe that we will fix this, ``meaningdetector/`` shouldn't be required in building the app at all as it is an utility for creating the app's configuration files and the ``opacapp`` does not depend on it.

**Comment by johan12345** [comment]
We could also replace the two JARs in the `opacapp/libs` folder related to the `cwac-adapter` and `cwac-endless` libraries with Gradle dependencies, but we would need to add an extra Gradle source server for that because they are not available on Maven Central or JCenter as far as I know.

**Comment by raphaelm** [comment]
The CWAC libraries *are* in Maven Central, but not in ``aar`` format, only as ``apklib`` and ``pom``. Since the ``cwac-endless`` page says the project is retired, I don't really like the thought of making our build process dependend on CommonsWare's servers (althought I don't think it will vanish from there) and I think we should rather keep the ``jar`` for now..

**Comment by johan12345** [comment]
Oh, okay. Then let's keep the JARs :)
