### ISSUE TITLE
Display media type icon in starred list

### ISSUE THREAD

**Issue by raphaelm** [raphaelm/opacclient#321]

**Comment by johan12345** [comment]
This would need to be combined with an ability to refresh the saved data for the entries of the starred list (otherwise only new entries would get an icon). And if we do that, it wouldn't be much more effort to also create a cache for the whole detail view of starred items (internal issue ID OA-113).

**Comment by raphaelm** [comment]
No, this would not need the ability to refresh. I think it is perfectly valid to enable this feature only for new entries.

Of course, the ability to refresh and cache the whole details would be nice, but is much more than is necessary for this minor feature.
